name: GoStraightPlugin
version: ${project.version}
main: net.kunmc.lab.gostraightplugin.GoStraightPlugin
api-version: 1.15
authors: [ YukiAt ]

commands:
  gostraight:
    permission: gostraightplugin.gostraight

permissions:
  gostraightplugin.gostraight:
    default: op
